name: Deploy Website

on:
  push:
    branches:
      - main  # Replace with your main branch name if different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs # Adjust if your Jekyll site is in a subdirectory
          destination: ./docs/_site # Adjust if your build output directory is different

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
